Homework
FadeiKholyavo/webix-start pull request #3
Opened 2021-04-08 15:08 UTC by FadeiKholyavo

2021-04-08 16:08 UTC, VeraOrekh requested changes

2021-04-08 16:08 UTC, VeraOrekh commented on js/main.js
> +    id: "main ui",
Здесь будет лучше использовать camelCase, как в остальных случаях для id

2021-04-08 16:08 UTC, VeraOrekh commented on js/section.js
> +    if($$(form.id).validate()){
Желательно создать переменную, в которой будет ссылка на элемент формы (чтобы два раза не вызывать $$)

2021-04-08 16:08 UTC, VeraOrekh commented on js/section.js
> +        let item = $$(form.id).getValues();
Т.к. значение переменной item не изменяется, лучше будет использовать const

2021-04-08 16:08 UTC, VeraOrekh commented on js/section.js
> +        $$(dataTable.id).add(item)
Не забывай про точки с запятой, ниже тоже в очень многих случаях опущено

2021-04-08 16:08 UTC, VeraOrekh commented on js/section.js
> +            return value > 1970 && value < new Date().getFullYear()
Крайние значения (1970 и 2021) нельзя добавить. 
Ещё, т.к. year, rating, votes должны быть числовыми значениями, можешь добавить проверку webix.rules.isNumber.
Ещё у ui.text есть свойство type: number. Можешь использовать один из двух методов

2021-04-08 20:51 UTC, VeraOrekh commented on js/section.js
> +        {}
Я бы на твоём месте тут не добавляла спейсер в элементы формы, а создала бы layout: 
rows: [form, {}]

2021-04-08 21:30 UTC, VeraOrekh approved these changes

2021-04-09 08:16 UTC, Zwillinge requested changes

2021-04-09 08:16 UTC, Zwillinge commented on js/section.js
> +    const filmForm = $$(form.id);
я бы посоветовала избегать такого обращения к id, заданного внутри объектов. не всегда тебе будет доступен сам конфигурационный объект виджета. более конвенционально обращаться по строчному id
также

2021-04-09 08:16 UTC, Zwillinge commented on js/main.js
> +    id: "mainUi",
mainUi нигде не используется

2021-04-09 08:16 UTC, Zwillinge commented on data/testdata.js
> +	{ id:1, title:"The Shawshank Redemption",       year:1994, votes:678790, raiting:9.2, rank:1},
а зачем менять грамматически праввильное слово на неправильное?
в будущем у вас будет json с тысячей записей, с тем же полем.

2021-04-09 08:42 UTC, Zwillinge commented on js/section.js
> +    const filmForm = $$(form.id);
`$$('filmForm');` - а ведь везде в прилоджении уже двойные кавычки
также убери пожалуйста console.log

2021-04-09 08:51 UTC, Zwillinge approved these changes

2021-04-09 09:44 UTC, merged